# Generated by Django 4.0.4 on 2022-05-06 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memebership',
            name='authority',
        ),
        migrations.AddField(
            model_name='memebership',
            name='member_authority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_authority', to='users.authority'),
        ),
    ]
