# Generated by Django 4.0.4 on 2022-05-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='member_of',
        ),
        migrations.AddField(
            model_name='membership',
            name='member_of',
            field=models.ManyToManyField(related_name='member_type', to='users.division'),
        ),
    ]
