# Generated by Django 4.0.4 on 2022-05-07 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_of',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_type', to='users.division'),
        ),
    ]
