# Generated by Django 4.0.4 on 2022-05-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_memebership_authority_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memebership',
            old_name='user_id',
            new_name='school_id',
        ),
    ]
