# Generated by Django 4.0.4 on 2022-05-07 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_membership_member_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='member_of',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_type', to='users.division'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
