# Generated by Django 4.0.4 on 2022-05-08 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_membership_member_of_alter_user_email'),
        ('users', '0003_alter_user_email'),
    ]

    operations = [
    ]
