# Generated by Django 4.0.4 on 2022-05-07 06:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_memebership_membership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
