# Generated by Django 4.0.4 on 2022-05-07 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoreboard',
            old_name='description',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='scoreboard',
            name='image',
        ),
    ]
